import { config } from './data/config.js'
import { locale } from './i18n.js'

export function getTopChampionsForLeague(patch, league)
{
  const lang = locale()
  var data = require('./data/patches/'+ lang + '/'+ patch.split(".").join("") +'.json')
  return data["top_champions"][league]
}

export function getBuffsList(patch)
{
  const lang = locale()
  var data = require('./data/patches/'+ lang + '/'+ patch.split(".").join("") +'.json')
  return data["buffs"]
}

export function getNerfsList(patch)
{
  const lang = locale()
  var data = require('./data/patches/'+ lang + '/'+ patch.split(".").join("") +'.json')
  return data["nerfs"]
}

export function getUpdatesList(patch)
{
  const lang = locale()
  var data = require('./data/patches/'+ lang + '/'+ patch.split(".").join("") +'.json')
  return data["updates"]
}

export function getCurrentPatch(){
  return config["currentPatch"]
}
export function getChampionsTiles()
{
  return {
    'Aatrox': require('./assets/champion/Aatrox.png'),
    'Ahri': require('./assets/champion/Ahri.png'),
    'Akali': require('./assets/champion/Akali.png'),
    'Alistar': require('./assets/champion/Alistar.png'),
    'Amumu': require('./assets/champion/Amumu.png'),
    'Anivia': require('./assets/champion/Anivia.png'),
    'Annie': require('./assets/champion/Annie.png'),
    'Ashe': require('./assets/champion/Ashe.png'),
    'AurelionSol': require('./assets/champion/AurelionSol.png'),
    'Azir': require('./assets/champion/Azir.png'),
    'Bard': require('./assets/champion/Bard.png'),
    'Blitzcrank': require('./assets/champion/Blitzcrank.png'),
    'Brand': require('./assets/champion/Brand.png'),
    'Braum': require('./assets/champion/Braum.png'),
    'Caitlyn': require('./assets/champion/Caitlyn.png'),
    'Camille': require('./assets/champion/Camille.png'),
    'Cassiopeia': require('./assets/champion/Cassiopeia.png'),
    'Chogath': require('./assets/champion/Chogath.png'),
    'Corki': require('./assets/champion/Corki.png'),
    'Darius': require('./assets/champion/Darius.png'),
    'Diana': require('./assets/champion/Diana.png'),
    'Draven': require('./assets/champion/Draven.png'),
    'DrMundo': require('./assets/champion/DrMundo.png'),
    'Ekko': require('./assets/champion/Ekko.png'),
    'Elise': require('./assets/champion/Elise.png'),
    'Evelynn': require('./assets/champion/Evelynn.png'),
    'Ezreal': require('./assets/champion/Ezreal.png'),
    'Fiddlesticks': require('./assets/champion/Fiddlesticks.png'),
    'Fiora': require('./assets/champion/Fiora.png'),
    'Fizz': require('./assets/champion/Fizz.png'),
    'Galio': require('./assets/champion/Galio.png'),
    'Gangplank': require('./assets/champion/Gangplank.png'),
    'Garen': require('./assets/champion/Garen.png'),
    'Gnar': require('./assets/champion/Gnar.png'),
    'Gragas': require('./assets/champion/Gragas.png'),
    'Graves': require('./assets/champion/Graves.png'),
    'Hecarim': require('./assets/champion/Hecarim.png'),
    'Heimerdinger': require('./assets/champion/Heimerdinger.png'),
    'Illaoi': require('./assets/champion/Illaoi.png'),
    'Irelia': require('./assets/champion/Irelia.png'),
    'Ivern': require('./assets/champion/Ivern.png'),
    'Janna': require('./assets/champion/Janna.png'),
    'JarvanIV': require('./assets/champion/JarvanIV.png'),
    'Jax': require('./assets/champion/Jax.png'),
    'Jayce': require('./assets/champion/Jayce.png'),
    'Jhin': require('./assets/champion/Jhin.png'),
    'Jinx': require('./assets/champion/Jinx.png'),
    'Kaisa': require('./assets/champion/Kaisa.png'),
    'Kalista': require('./assets/champion/Kalista.png'),
    'Karma': require('./assets/champion/Karma.png'),
    'Karthus': require('./assets/champion/Karthus.png'),
    'Kassadin': require('./assets/champion/Kassadin.png'),
    'Katarina': require('./assets/champion/Katarina.png'),
    'Kayle': require('./assets/champion/Kayle.png'),
    'Kayn': require('./assets/champion/Kayn.png'),
    'Kennen': require('./assets/champion/Kennen.png'),
    'Khazix': require('./assets/champion/Khazix.png'),
    'Kindred': require('./assets/champion/Kindred.png'),
    'Kled': require('./assets/champion/Kled.png'),
    'KogMaw': require('./assets/champion/KogMaw.png'),
    'Leblanc': require('./assets/champion/Leblanc.png'),
    'LeeSin': require('./assets/champion/LeeSin.png'),
    'Leona': require('./assets/champion/Leona.png'),
    'Lissandra': require('./assets/champion/Lissandra.png'),
    'Lucian': require('./assets/champion/Lucian.png'),
    'Lulu': require('./assets/champion/Lulu.png'),
    'Lux': require('./assets/champion/Lux.png'),
    'Malphite': require('./assets/champion/Malphite.png'),
    'Malzahar': require('./assets/champion/Malzahar.png'),
    'Maokai': require('./assets/champion/Maokai.png'),
    'MasterYi': require('./assets/champion/MasterYi.png'),
    'MissFortune': require('./assets/champion/MissFortune.png'),
    'MonkeyKing': require('./assets/champion/MonkeyKing.png'),
    'Mordekaiser': require('./assets/champion/Mordekaiser.png'),
    'Morgana': require('./assets/champion/Morgana.png'),
    'Nami': require('./assets/champion/Nami.png'),
    'Nasus': require('./assets/champion/Nasus.png'),
    'Nautilus': require('./assets/champion/Nautilus.png'),
    'Neeko': require('./assets/champion/Neeko.png'),
    'Nidalee': require('./assets/champion/Nidalee.png'),
    'Nocturne': require('./assets/champion/Nocturne.png'),
    'Nunu': require('./assets/champion/Nunu.png'),
    'Olaf': require('./assets/champion/Olaf.png'),
    'Orianna': require('./assets/champion/Orianna.png'),
    'Ornn': require('./assets/champion/Ornn.png'),
    'Pantheon': require('./assets/champion/Pantheon.png'),
    'Poppy': require('./assets/champion/Poppy.png'),
    'Pyke': require('./assets/champion/Pyke.png'),
    'Quinn': require('./assets/champion/Quinn.png'),
    'Rakan': require('./assets/champion/Rakan.png'),
    'Rammus': require('./assets/champion/Rammus.png'),
    'RekSai': require('./assets/champion/RekSai.png'),
    'Renekton': require('./assets/champion/Renekton.png'),
    'Rengar': require('./assets/champion/Rengar.png'),
    'Riven': require('./assets/champion/Riven.png'),
    'Rumble': require('./assets/champion/Rumble.png'),
    'Ryze': require('./assets/champion/Ryze.png'),
    'Sejuani': require('./assets/champion/Sejuani.png'),
    'Shaco': require('./assets/champion/Shaco.png'),
    'Shen': require('./assets/champion/Shen.png'),
    'Shyvana': require('./assets/champion/Shyvana.png'),
    'Singed': require('./assets/champion/Singed.png'),
    'Sion': require('./assets/champion/Sion.png'),
    'Sivir': require('./assets/champion/Sivir.png'),
    'Skarner': require('./assets/champion/Skarner.png'),
    'Sona': require('./assets/champion/Sona.png'),
    'Soraka': require('./assets/champion/Soraka.png'),
    'Swain': require('./assets/champion/Swain.png'),
    'Sylas': require('./assets/champion/Sylas.png'),
    'Syndra': require('./assets/champion/Syndra.png'),
    'TahmKench': require('./assets/champion/TahmKench.png'),
    'Taliyah': require('./assets/champion/Taliyah.png'),
    'Talon': require('./assets/champion/Talon.png'),
    'Taric': require('./assets/champion/Taric.png'),
    'Teemo': require('./assets/champion/Teemo.png'),
    'Thresh': require('./assets/champion/Thresh.png'),
    'Tristana': require('./assets/champion/Tristana.png'),
    'Trundle': require('./assets/champion/Trundle.png'),
    'Tryndamere': require('./assets/champion/Tryndamere.png'),
    'TwistedFate': require('./assets/champion/TwistedFate.png'),
    'Twitch': require('./assets/champion/Twitch.png'),
    'Udyr': require('./assets/champion/Udyr.png'),
    'Urgot': require('./assets/champion/Urgot.png'),
    'Varus': require('./assets/champion/Varus.png'),
    'Vayne': require('./assets/champion/Vayne.png'),
    'Veigar': require('./assets/champion/Veigar.png'),
    'Velkoz': require('./assets/champion/Velkoz.png'),
    'Vi': require('./assets/champion/Vi.png'),
    'Viktor': require('./assets/champion/Viktor.png'),
    'Vladimir': require('./assets/champion/Vladimir.png'),
    'Volibear': require('./assets/champion/Volibear.png'),
    'Warwick': require('./assets/champion/Warwick.png'),
    'Xayah': require('./assets/champion/Xayah.png'),
    'Xerath': require('./assets/champion/Xerath.png'),
    'XinZhao': require('./assets/champion/XinZhao.png'),
    'Yasuo': require('./assets/champion/Yasuo.png'),
    'Yorick': require('./assets/champion/Yorick.png'),
    'Yuumi': require('./assets/champion/Yuumi.png'),
    'Zac': require('./assets/champion/Zac.png'),
    'Zed': require('./assets/champion/Zed.png'),
    'Ziggs': require('./assets/champion/Ziggs.png'),
    'Zilean': require('./assets/champion/Zilean.png'),
    'Zoe': require('./assets/champion/Zoe.png'),
    'Zyra': require('./assets/champion/Zyra.png'),

  }
}

export function getRoleIcons()
{
  return {
    'top': require('./assets/roles/Top_icon.png'),
    'jg': require('./assets/roles/Jungle_icon.png'),
    'mid': require('./assets/roles/Middle_icon.png'),
    'adc': require('./assets/roles/Bottom_icon.png'),
    'sup': require('./assets/roles/Support_icon.png')
  }
}

export function getLeagueIcons()
{
  return {
    'iron': require('./assets/leagues/iron.png'),
    'bronze': require('./assets/leagues/bronze.png'),
    'silver': require('./assets/leagues/silver.png'),
    'gold': require('./assets/leagues/gold.png'),
    'platinum': require('./assets/leagues/platinum.png'),
    'diamond': require('./assets/leagues/diamond.png')
  }
}

export function getChampionRotationID(){
  var data = require('./data/champion/freerotation.json')
  return data["freeChampionIds"]
}


export function getChampionsID(){
  return{
    266 : 'Aatrox',
    103 : 'Ahri',
    84 :  'Akali',
    32 : 'Amumu',
    34 : 'Anivia',
    1 : 'Annie',
    22 : 'Ashe',
    136 : 'AurelionSol',
    268 : 'Azir',
    432 : 'Bard',
    53 : 'Blitzcrank',
    63 : 'Brand',
    201 : 'Braum',
    51 : 'Caytlin',
    164 : 'Camille',
    69 : 'Cassiopeia',
    31 : 'Chogath',
    42 : 'Corki',
    122 : 'Darius',
    131 : 'Diana',
    36 : 'DrMundo',
    119 : 'Draven',
    245 : 'Ekko',
    60 : 'Elise',
    28 : 'Evelynn',
    81 : 'Ezreal',
    9 : 'FiddleSticks',
    114 : 'Fiora',
    105 : 'Fizz',
    3 : 'Galio',
    41 : 'Gangplank',
    86 : 'Garen',
    150 : 'Gnar',
    79 : 'Gragas',
    104 : 'Graves',
    120 : 'Hecarim',
    74 : 'Heimerdinger',
    420 : 'Illaoi',
    39 : 'Irelia',
    427 : 'Ivern',
    40 : 'Janna',
    59 : 'JarvanIV',
    24 : 'Jax',
    126 : 'Jayce',
    202 : 'Jhin',
    222 : 'Jinx',
    429 : 'Kalista',
    43 : 'Karma',
    30 : 'Karthus',
    38 : 'Kassadin',
    55 : 'Katarina',
    10 : 'Kayle',
    141 : 'Kayn',
    85 : 'Kennen',
    121 : 'Khazix',
    203 : 'Kindred',
    240 : 'Kled',
    96 : 'KogMaw',
    7 : 'LeBlanc',
    64 : 'LeeSin',
    89 : 'Leona',
    127 : 'Lissandra',
    236 : 'Lucian',
    117 : 'Lulu',
    99 : 'Lux',
    54 : 'Malphite',
    90 : 'Malzahar',
    57 : 'Maokai',
    11 : 'MasterYi',
    21 : 'MissFortune',
    82 : 'Mordekaiser',
    25 : 'Morgana',
    267 : 'Nami',
    75 : 'Nasus',
    111 : 'Nautilus',
    76 : 'Nidalee',
    56 : 'Nocturne',
    20 : 'Nunu',
    2 : 'Olaf',
    61 : 'Orianna',
    516 : 'Ornn',
    80 : 'Pantheon',
    78 : 'Poppy',
    133 : 'Quinn',
    497 : 'Rakkan',
    33 : 'Rammus',
    421 : 'RekSai',
    58 : 'Renekton',
    107 : 'Rengar',
    92 : 'Riven',
    68 : 'Rumble',
    13 : 'Ryze',
    113 : 'Sejuani',
    35 : 'Shaco',
    98 : 'Shen',
    102 : 'Shyvana',
    27 : 'Singed',
    14 : 'Sion',
    15 : 'Sivir',
    72 : 'Skarner',
    37 : 'Sona',
    16 : 'Soraka',
    50 : 'Swain',
    134 : 'Syndra',
    223 : 'TahmKench',
    163 : 'Taliyah',
    91 : 'Talon',
    44 : 'Taric',
    17 : 'Teemo',
    412 : 'Thresh',
    18 : 'Tristana',
    48 : 'Trundle',
    23 : 'Tryndamere',
    4 : 'TwistedFate',
    29 : 'Twitch',
    77 : 'Udyr',
    6 : 'Urgot',
    110 : 'Varus',
    67 : 'Vayne',
    45 : 'Veigar',
    161 : 'VelKoz',
    254 : 'Vi',
    112 : 'Viktor',
    8 : 'Vladimir',
    106 : 'Volibear',
    19 : 'Warwick',
    62 : 'Wukong',
    498 : 'Xayah',
    101 : 'Xerath',
    5 : 'XinZhao',
    157 : 'Yasuo',
    83 : 'Yorick',
    154 : 'Zac',
    238 : 'Zed',
    115 : 'Ziggs',
    26 : 'Zilean',
    142 :'Zoe',
    143 : 'Zyra'
  }
}
